#!/bin/bash

sudo su
yum install -y git
cd /tmp                    # to know where we are in script
git clone https://github.com/nic-instruction/hello-nti-310.git
yum install -y openldap-servers openldap-clients
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
chown ldap. /var/lib/ldap/DB_CONFIG     #change ownership
systemctl enable slapd
systemctl start slapd
yum install -y httpd phpldapadmin
setsebool -P httpd_can_connect_ldap on
systemctl enable httpd
systemctl start httpd
sed -i 's,Require local,#Require local\n   Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf
unalias cp

echo "*.info;mail.none;authpriv.none;cron.none   @10.128.0.5" >> /etc/rsyslog.conf && systemctl restart rsyslog.service
