#!/bin/bash

yum -y install nagios           #install, start and enable nagios
systemctl enable nagios
systemctl start nagios

setenforce 0                    # turn off SELinux, so it doesn't trip us up

systemctl enable httpd          # Enable and start apache
systemctl start httpd

yum -y install nrpe             #install, enable, and start nrpe, the nagios client
systemctl enable nrpe
systemctl start nrpe
yum -y install nagios-plugins-all
yum -y install nagios-plugins-nrpe

htpasswd -b /etc/nagios/passwd nagiosadmin nagiosadmin      #set the nagios admin password
sed i 's,allowed_hosts=127.0.0.1,allowed_hosts=127.0.0.1\,10.128.0.0\/20,g' /etc/nagios/nrpe.cfg
#enables connections from the subnet please adjust to your subnet.

sed -i 's,dont_blame_nrpe=0,dont_blame_nrpe=1,g' /etc/nagios/nrpe.cfg
#enables NRPE monitoring

mkdir /etc/nagios/servers
#create a directory for our server configuration and enable it in the config file
sed -i 's,#cfg_dir=/etc/nagios/servers,cfg_dir=/etc/nagios/servers,g' /etc/nagios/nagios.cfg
systemctl restart nagios

cd /etc/nagios/servers

#now take a break to spin up a machine called example-a with all the nrpe plugins installed and a properly configured path
# to nagios
# put its ip address into the address column below

echo '# Define a host for an example-a machine
